# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_appcustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcustomization',
            name='custom_helpdesk_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
