# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180313_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcustomization',
            name='footer_image_left',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='appcustomization',
            name='footer_image_right',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
