# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180314_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomization',
            name='footer_image_left',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='appcustomization',
            name='footer_image_right',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
