# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180314_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receives_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
