# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180405_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcustomization',
            name='email_language_toggle',
            field=models.BooleanField(default=True, verbose_name='Display all system languages in emails'),
        ),
    ]
