# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appcustomization_email_language_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcustomization',
            name='product_department',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
