# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_appcustomization_product_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcustomization',
            name='do_not_reply_email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
