# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_fail_silently',
            field=models.BooleanField(default=False, verbose_name='Fail Silently'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_timeout',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Email send timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=False, verbose_name='Use TSL'),
        ),
    ]
