# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-17 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180803_1036'),
        ('core', '0023_securityquestions'),
    ]

    operations = [
    ]
