# Generated by Django 2.1.5 on 2019-02-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20181017_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('last_login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_logins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AppCustomization',
        ),
        migrations.RemoveField(
            model_name='previouslogins',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.DeleteModel(
            name='PreviousLogins',
        ),
        migrations.AlterUniqueTogether(
            name='previouslogin',
            unique_together={('user', 'ip', 'user_agent')},
        ),
    ]
