# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-08 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_appcustomization_do_not_reply_email'),
        ('core', '0025_merge_20181017_2041'),
    ]

    operations = [
    ]
