# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmembership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('how', models.CharField(max_length=50)),
                ('howmore', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
