# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmembership', '0003_limbouser_accepted_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limbouser',
            name='accepted_terms',
        ),
        migrations.AddField(
            model_name='limbouser',
            name='password',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
