# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmembership', '0004_auto_20180417_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limbouser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
