# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmembership', '0005_auto_20180417_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='limbouser',
            name='accepted_terms',
            field=models.BooleanField(default=True),
        ),
    ]
