# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshdesk', '0002_configuration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.RunSQL([('INSERT INTO freshdesk_configuration (url, secret_key) values (%s, %s)', ['https://gccollab.gctools-outilsgc.ca/'], [''])])
    ]
