# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 08:14
from __future__ import unicode_literals

from ..helpers import unique_idp_metadata_filepath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0011_auto_20180403_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='metadata_filename',
            field=models.FileField(blank=True, upload_to=unique_idp_metadata_filepath),
        ),
    ]
