# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_auto_20180718_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='activate_site_configuration',
            field=models.BooleanField(default=False),
        ),
    ]
